name: dtmtest
description: "Project for test"
publish_to: "none"
version: 1.0.0+0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^8.1.2
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  easy_localization: ^3.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  excel: ^4.0.3
  file_picker: ^8.0.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.1
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  internet_connection_checker: ^1.0.0+1
  intl: 0.18.1
  html: ^0.15.4
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  custom_refresh_indicator: ^3.1.0
  path_provider: ^2.1.3
  connectivity_plus: 5.0.2

dev_dependencies:
  auto_route_generator: ^8.0.0
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter_gen:
  output: lib/common/res/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/colors/
    - assets/icons/
    - assets/images/
    - assets/l10n/
    - assets/files/
    - assets/text/

  fonts:
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText-Bold.ttf
        - asset: assets/fonts/CrimsonText-BoldItalic.ttf
        - asset: assets/fonts/CrimsonText-Italic.ttf
        - asset: assets/fonts/CrimsonText-Regular.ttf
        - asset: assets/fonts/CrimsonText-SemiBold.ttf
        - asset: assets/fonts/CrimsonText-SemiBoldItalic.ttf
