// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHyT6gl7Hs39Rs8F0GMaBYyrPUs8cpnV8',
    appId: '1:3117428222:web:c15406cd61be84ec60e4af',
    messagingSenderId: '3117428222',
    projectId: 'dtmtest-49703',
    authDomain: 'dtmtest-49703.firebaseapp.com',
    storageBucket: 'dtmtest-49703.appspot.com',
    measurementId: 'G-0P248HTQRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH44ywqd8A6RCEg5yF-S-ZmqkE3UO8YtA',
    appId: '1:3117428222:android:dd117ae33f435bfe60e4af',
    messagingSenderId: '3117428222',
    projectId: 'dtmtest-49703',
    storageBucket: 'dtmtest-49703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_m8U9rYKUqkbiu1cOlNmApjV2_MjN2Ag',
    appId: '1:3117428222:ios:d386947c0363400b60e4af',
    messagingSenderId: '3117428222',
    projectId: 'dtmtest-49703',
    storageBucket: 'dtmtest-49703.appspot.com',
    androidClientId: '3117428222-d86hfsd15vd1h6s932s1bsst8s05okjs.apps.googleusercontent.com',
    iosClientId: '3117428222-90sr9er5udle6c35rteq17dtsght6v1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtmtest',
  );
}
